### ISSUE TITLE
Inconsistent Delegate Voting Power

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-mondo#32]
## Description

On the delegate list page delegated votes is sometimes different than what is displayed on their page. 

<img width="1258" alt="Screenshot 2024-08-20 at 10 00 19 AM" src="https://github.com/user-attachments/assets/a9c842d2-f0d2-42cf-8155-208932e8c7b1">

<img width="361" alt="Screenshot 2024-08-20 at 9 59 48 AM" src="https://github.com/user-attachments/assets/adb805ee-0325-4038-bc0e-81f6869dbaaa">

**Comment by jmrossy** [comment]
@aaronmgdr hmm I wonder if one is showing the Delegate's personal voting power vs the amount of CELO delegated _to_ them

**Comment by aaronmgdr** [comment]
that would make sense and when i read the wording seems to be what it is saying after all. 

I feel like id want it to be that the same number is shown in both places. but this could be less of a true bug and more of a product decision

**Comment by aaronmgdr** [comment]
### SOLUTION

ON each delegatee's page page under "Delegatee's current voting power" add a label Delegated Votes with tthe number being same as on the index page

**Comment by aaronmgdr** [comment]
fixed with #65
