### ISSUE TITLE
Celo Mondo problem with withdraw

### ISSUE THREAD

**Issue by ritmocrypto** [celo-org/celo-mondo#37]
Hello, want to make test withdrawal in CELO MONDO after unstaking and unlocking some ammount of CELO. But at balance for withdraw didnt see nothing. Is there some lockdown period?
![Screenshot_20240826_091106_Samsung Internet](https://github.com/user-attachments/assets/ca6b9870-9f76-4b81-a6d5-c013adde7a2d)
![Uploading Screenshot_20240826_091126_Samsung Internet.jpg…]()

**Comment by Khan-arsh** [comment]
I’ve same issue were you able to withdraw?

**Comment by laalauren1** [comment]
@Khan-arsh Are you able yo withdraw now ?

**Comment by laalauren1** [comment]
@ritmocrypto You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID CEL07638
Please see the link below to our dedicated support line:
[Celo live support](https://thedappsupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by aaronmgdr** [comment]
i assume that was the issue? if not what is your address?

**Comment by aaronmgdr** [comment]
1 is there a problem. 2 should UI to make clear gold is in unlocking period
