### ISSUE TITLE
Create SAFE APP

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-mondo#57]
## Problem

people want to be able to connect to mondo via a Safe multisig
## Solution

create a safe app seems to mostly be a manifest and a connector (https://github.com/safe-global/safe-apps-sdk/tree/main/packages/safe-apps-wagmi)

###  how to

this guide shows how to create safe apps The process should be straight forward and not take too long. Here's a guide. (https://help.safe.global/en/articles/145503-how-to-create-a-safe-app-with-safe-apps-sdk-and-list-ithttps://help.safe.global/en/articles/145503-how-to-create-a-safe-app-with-safe-apps-sdk-and-list-it)

**Comment by aaronmgdr** [comment]
proposed by @LuukDAO

**Comment by nicolasbrugneaux** [comment]
Investigated and everything is already setup, but the CORS rules and the manifest.json, will add these asap.
