### ISSUE TITLE
Link Delegator adresses to block explorer

### ISSUE THREAD

**Issue by work-0xj4an** [celo-org/celo-mondo#73]
Allow people to click on the delegators addresses that have delegated to a delegate and open the CeloScan of this Address
## Problem
If somebody wants to check the Delegators Addresses that have delegated tokens to a Delegate they Can't, celo mondo only shows the firs 6 characters and the last 4 characters of the address.
<img width="328" alt="image" src="https://github.com/user-attachments/assets/cc4789eb-0c21-476b-8ba8-5964db4d5d8a">

## Solution
Ideally we can make those addresses links to the Celoscan in the way https://celoscan.io/address/XXXXXXXXXX, also will be good to the the same for the Delegate Address.

## Alternatives
At least allow people to copy and paste those addresses the same way they can copy and paste the address of the Delegate.
<img width="265" alt="image" src="https://github.com/user-attachments/assets/e1e5f3f5-1dbc-4567-9fc8-ac2dcabaeaa9">

**Comment by work-0xj4an** [comment]
@aaronmgdr I forgot to mention will be also good to Include a count of how many voters each proposal get.
Include in the Detail:
<img width="362" alt="image" src="https://github.com/user-attachments/assets/01b7b6ce-b90a-4b89-b0d1-f4a98e34625a">

Also Include in the Overview.
<img width="621" alt="image" src="https://github.com/user-attachments/assets/72b25530-f305-475c-9cd0-24677a05f701">

**Comment by nicolasbrugneaux** [comment]
The hidden comment above has been ported to its own issue
- https://github.com/celo-org/celo-mondo/issues/104
